# Variable Group 'ciBuildiNumber' was defined in the Variables tab
trigger:
  branches:
    include:
    - refs/heads/main
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: aks-terra
  steps:
  - checkout: self
  - task: Docker@2
    displayName: buildAndPush
    inputs:
      containerRegistry: 14e463a1-8612-4f35-9ec3-3e1422949b62
      repository: goapp
      tags: >-
        $(Build.BuildId)

        latest
...
