# Variable Group 'ciBuildiNumber' was defined in the Variables tab
trigger:
  branches:
    include:
    - refs/heads/main
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool: aks-terra
  steps:
  - checkout: self
  - task: Docker@0
    displayName: Build an image
    inputs:
      azureSubscriptionEndpoint: daa50109-9451-405c-9452-e0e87337fe37
      azureContainerRegistry: '{"loginServer":"ors10.azurecr.io", "id" : "/subscriptions/2fd209e4-5958-4637-8883-3debc61d1654/resourceGroups/aks-shared/providers/Microsoft.ContainerRegistry/registries/ors10"}'
      imageName: goapp:$(Build.BuildId)
  - task: Docker@0
    displayName: Push an image
    inputs:
      azureSubscriptionEndpoint: daa50109-9451-405c-9452-e0e87337fe37
      azureContainerRegistry: '{"loginServer":"ors10.azurecr.io", "id" : "/subscriptions/2fd209e4-5958-4637-8883-3debc61d1654/resourceGroups/aks-shared/providers/Microsoft.ContainerRegistry/registries/ors10"}'
      action: Push an image
      imageName: goapp:$(Build.BuildId)
  - task: PublishPipelineArtifact@1
    displayName: Publish Pipeline Artifact
    inputs:
      artifactName: goappBuild
...
